services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL}

    container_name: smart-pos-ui

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env.local

    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"